import Foundation

enum L10n {
    static func languageCode(_ preference: String? = nil) -> String {
        let selected = preference ?? UserDefaults.standard.string(forKey: "appLanguage")
        if selected == SettingsStore.Language.english.rawValue { return "en" }
        if selected == SettingsStore.Language.vietnamese.rawValue { return "vi" }
        let preferred = Locale.preferredLanguages.first?.lowercased() ?? "en"
        return preferred.hasPrefix("vi") ? "vi" : "en"
    }

    static func locale(_ preference: String? = nil) -> Locale {
        Locale(identifier: languageCode(preference) == "vi" ? "vi_VN" : "en_US")
    }

    static func t(_ key: String, _ preference: String? = nil) -> String {
        let table = languageCode(preference) == "vi" ? vi : en
        return table[key] ?? en[key] ?? vi[key] ?? key
    }

    static func f(_ key: String, _ preference: String? = nil, _ args: CVarArg...) -> String {
        String(format: t(key, preference), locale: locale(preference), arguments: args)
    }

    static func duration(_ seconds: Double, preference: String? = nil) -> String {
        let code = languageCode(preference)
        if seconds >= 3600 {
            let value = Int(seconds / 3600)
            return code == "vi" ? "\(value) giờ" : "\(value) hour" + (value == 1 ? "" : "s")
        }
        if seconds >= 60 {
            let value = Int(seconds / 60)
            return code == "vi" ? "\(value) phút" : "\(value) minute" + (value == 1 ? "" : "s")
        }
        let value = Int(seconds)
        return code == "vi" ? "\(value) giây" : "\(value) second" + (value == 1 ? "" : "s")
    }

    static func relativeUpdated(from date: Date, preference: String? = nil) -> String {
        let seconds = Int(Date().timeIntervalSince(date))
        if seconds < 5 { return t("time.justUpdated", preference) }
        if seconds < 60 { return f("time.secondsAgo", preference, seconds) }
        if seconds < 3600 { return f("time.minutesAgo", preference, seconds / 60) }
        return f("time.hoursAgo", preference, seconds / 3600)
    }

    static func resetCountdown(to date: Date, preference: String? = nil) -> String {
        let seconds = max(0, Int(date.timeIntervalSinceNow))
        if seconds <= 0 { return t("quota.resetSoon", preference) }
        let days = seconds / 86_400
        let hours = (seconds % 86_400) / 3_600
        let minutes = (seconds % 3_600) / 60
        if days > 0 { return f("quota.resetInDaysHours", preference, days, hours) }
        if hours > 0 { return f("quota.resetInHoursMinutes", preference, hours, minutes) }
        return f("quota.resetInMinutes", preference, minutes)
    }

    static func windowLabel(_ label: String, preference: String? = nil) -> String {
        guard languageCode(preference) == "en" else { return label }
        var value = label
        let replacements = [
            "Giới hạn": "Limit",
            "Tuần": "Week",
            "tuần": "weeks",
            "ngày": "days",
            "giờ": "hours",
            "phút": "minutes",
        ]
        for (source, target) in replacements {
            value = value.replacingOccurrences(of: source, with: target)
        }
        return value
    }

    static func dayMonth(_ date: Date, preference: String? = nil) -> String {
        let formatter = DateFormatter()
        formatter.locale = locale(preference)
        formatter.dateFormat = languageCode(preference) == "vi" ? "d MMM" : "MMM d"
        return formatter.string(from: date)
    }

    private static let vi: [String: String] = [
        "language.system": "Theo hệ thống",
        "language.english": "English",
        "language.vietnamese": "Tiếng Việt",
        "settings.tab.general": "Cài chung",
        "settings.tab.providers": "Nhà cung cấp",
        "settings.tab.display": "Hiển thị",
        "settings.tab.advanced": "Nâng cao",
        "settings.tab.about": "Giới thiệu",
        "settings.tab.debug": "Debug",
        "settings.section.system": "Hệ thống",
        "settings.section.usage": "Sử dụng",
        "settings.section.automation": "Tự động",
        "settings.section.privacy": "Riêng tư",
        "settings.section.developer": "Nhà phát triển",
        "settings.section.files": "Tệp",
        "settings.section.menuBar": "Menu bar",
        "settings.section.links": "Liên kết",
        "settings.section.setup": "Thiết lập",
        "settings.section.account": "Tài khoản",
        "settings.section.quotaWarnings": "Cảnh báo quota",
        "settings.language.title": "Ngôn ngữ",
        "settings.language.subtitle": "Đổi ngay trong UI; lần mở sau app cũng giữ ngôn ngữ này.",
        "settings.launchAtLogin.title": "Khởi động cùng máy",
        "settings.launchAtLogin.subtitle": "Tự mở BirdNion khi đăng nhập.",
        "settings.refreshFrequency.title": "Tần suất làm mới",
        "settings.refreshFrequency.subtitle": "Mỗi bao lâu app gọi lại nhà cung cấp.",
        "settings.statusChecks.title": "Kiểm tra trạng thái",
        "settings.statusChecks.subtitle": "Poll trang trạng thái của các nhà cung cấp.",
        "settings.sessionNotifications.title": "Thông báo phiên 5 giờ",
        "settings.sessionNotifications.subtitle": "Báo khi phiên quota chạm 0% và khi khôi phục.",
        "settings.quotaWarningNotifications.title": "Thông báo cảnh báo quota",
        "settings.quotaWarningNotifications.subtitle": "Cảnh báo khi còn dưới ngưỡng đã đặt.",
        "settings.warningThreshold.title": "Ngưỡng cảnh báo",
        "settings.warningThreshold.subtitle": "Báo lần đầu khi % còn lại chạm mức này.",
        "settings.criticalThreshold.title": "Ngưỡng nguy hiểm",
        "settings.criticalThreshold.subtitle": "Báo lần nữa khi chạm mức thấp hơn này.",
        "settings.hidePersonalInfo.title": "Ẩn thông tin cá nhân",
        "settings.hidePersonalInfo.subtitle": "Che email tài khoản trên chip và popover.",
        "settings.debugMenu.title": "Hiện mục Debug",
        "settings.debugMenu.subtitle": "Thêm tab Debug để xem log và cache.",
        "settings.developer.footer": "Một số thay đổi kỹ thuật vẫn có thể cần mở lại app.",
        "settings.display.footer": "Cài đặt này sẽ có hiệu lực khi trình render hỗ trợ multi-icon.",
        "settings.mergeIcons.title": "Gộp icon nhà cung cấp",
        "settings.mergeIcons.subtitle": "Hiện một icon duy nhất xoay vòng giữa các provider.",
        "settings.switcherShowsIcons.title": "Switcher có icon",
        "settings.switcherShowsIcons.subtitle.on": "Hiện icon khi chuyển nhà cung cấp từ popover.",
        "settings.switcherShowsIcons.subtitle.off": "Bật “Gộp icon” trước.",
        "settings.debug.footer": "Để xem log probe / fetch strategy thật, mở Console.app và filter theo bundle ID.",
        "settings.configFile.title": "File cấu hình",
        "settings.openFinder": "Mở Finder",
        "about.openProject": "Mở trang dự án trên GitHub",
        "about.tagline": "Theo dõi quota AI ngay trên menu bar.",
        "about.version": "phiên bản %@ (%@)",
        "provider.search": "Tìm nhà cung cấp",
        "provider.clearSearch": "Xóa",
        "provider.reorderHelp": "Kéo để sắp xếp nhà cung cấp",
        "provider.choose": "Chọn một nhà cung cấp",
        "provider.enableHelp.on": "Tắt polling cho nhà cung cấp này",
        "provider.enableHelp.off": "Bật polling cho nhà cung cấp này",
        "provider.disabled": "Đã tắt",
        "provider.notLoaded": "Chưa tải",
        "provider.loading": "Đang tải…",
        "provider.errorPrefix": "Lỗi: %@",
        "provider.remaining": "Còn %d%%",
        "provider.status": "Trạng thái",
        "provider.source": "Nguồn",
        "provider.plan": "Gói",
        "provider.planName": "Tên gói",
        "provider.account": "Tài khoản",
        "provider.version": "Phiên bản",
        "provider.serviceStatus": "Tình trạng",
        "provider.resetCredits": "Reset khả dụng",
        "provider.codeReview": "Code review",
        "provider.creditsHistory": "Lịch sử credits",
        "provider.buyCredits": "Mua credits",
        "provider.openPage": "Mở trang",
        "provider.updated": "Cập nhật",
        "provider.reloadHelp": "Đọc lại settings.json và làm mới quota",
        "provider.noData.enabled": "Chưa có dữ liệu — bấm làm mới.",
        "provider.noData.disabled": "Đang tắt — không có dữ liệu.",
        "provider.reserve": "%d%% dự phòng",
        "provider.resetAfter": "Reset sau %@",
        "provider.enoughUntilReset": "Đủ dùng đến khi reset",
        "provider.mayRunOut": "Có thể hết trước khi reset",
        "provider.credits": "CREDITS",
        "provider.unlimited": "∞ Không giới hạn",
        "provider.creditsLeft": "%@ còn lại",
        "provider.outOfCredits": "Hết",
        "provider.cost": "CHI PHÍ",
        "provider.usedRemaining": "%d%% đã dùng · còn %@",
        "provider.today": "Hôm nay",
        "provider.last30": "30 ngày",
        "provider.email": "EMAIL",
        "provider.organization": "TỔ CHỨC",
        "provider.login": "LOGIN",
        "provider.accountLabel": "Nhãn tài khoản",
        "provider.accountLabelPlaceholder": "Tùy chọn — để trống để tự suy ra",
        "provider.signIn": "Đăng nhập",
        "provider.codexSignInHint": "Đăng nhập bằng lệnh `codex` trong Terminal.",
        "provider.dataSource": "Nguồn dữ liệu",
        "provider.menuBarMetric": "Menu bar hiển thị",
        "provider.apiRegion": "Khu vực API",
        "provider.refreshEvery": "Làm mới mỗi",
        "provider.defaultGlobal": "Mặc định = theo cài đặt chung (%@)",
        "provider.cookie": "Cookie",
        "provider.cookiePlaceholder": "Dán Cookie: header từ chatgpt.com",
        "provider.cookieClaude": "Cookie Claude",
        "provider.manualCookie": "Cookie header thủ công",
        "provider.manualCookieHelp": "Mở claude.ai trong trình duyệt đã đăng nhập → DevTools → Network → sao chép toàn bộ header `Cookie:`.",
        "provider.keychainOAuth": "Keychain OAuth",
        "provider.openAIWebExtras": "OpenAI web extras",
        "provider.openAIWebExtrasHelp": "Quét chatgpt.com (WebView ẩn) lấy code-review %, credits, lịch sử. Nặng pin/mạng — mặc định tắt.",
        "provider.claudeConfig": "Cấu hình Claude…",
        "provider.token": "Token",
        "provider.tokenPlaceholder": "Dán token vào đây",
        "provider.save": "Lưu",
        "provider.savedSettings": "Đã lưu vào ~/.config/birdnion/settings.json.",
        "provider.saveError": "Lỗi lưu: %@",
        "provider.quotaWarningsFooter": "Dùng ngưỡng chung trừ khi bật tùy chỉnh riêng cho từng cửa sổ.",
        "provider.sessionWindow": "Phiên (5 giờ)",
        "provider.weekWindow": "Tuần",
        "provider.customThresholds": "Tùy chỉnh ngưỡng %@",
        "provider.inherited": "Kế thừa: %@",
        "provider.warning": "Cảnh báo",
        "provider.critical": "Nguy hiểm",
        "provider.accountsFooter": "Mỗi tài khoản đăng nhập riêng. “Thêm tài khoản” mở `codex login` trong trình duyệt; tài khoản hệ thống (~/.codex) không bị ghi đè.",
        "provider.systemAccount": "Tài khoản hệ thống",
        "provider.accountGeneric": "Tài khoản",
        "provider.systemManaged": "Hệ thống · ~/.codex",
        "provider.appManaged": "Quản lý bởi app",
        "provider.reauth": "Đăng nhập lại",
        "provider.saveManaged": "Lưu thành managed",
        "provider.addAccount": "Thêm tài khoản",
        "provider.waitingLogin": "Đang chờ đăng nhập trong trình duyệt…",
        "provider.link.codexUsage": "Trang sử dụng Codex",
        "provider.link.openAIStatus": "Trạng thái OpenAI",
        "provider.link.changelog": "Changelog",
        "provider.link.minimaxPlan": "Trang Token Plan",
        "provider.link.openRouterCredits": "Tín dụng OpenRouter",
        "provider.link.apiKeys": "API keys",
        "provider.link.deepSeekBalance": "Số dư DeepSeek",
        "provider.link.codingPlan": "Coding Plan",
        "provider.link.anthropicStatus": "Trạng thái Anthropic",
        "provider.link.dashboard": "Bảng điều khiển",
        "provider.link.status": "Trạng thái dịch vụ",
        "provider.link.usage": "Trang sử dụng",
        "provider.link.subscription": "Gói đăng ký",
        "provider.link.billing": "Thanh toán",
        "source.auto": "Tự động",
        "source.oauth": "OAuth",
        "source.cli": "CLI",
        "source.codex.auto.subtitle": "OAuth, fallback sang CLI `codex app-server` khi lỗi (mặc định).",
        "source.codex.oauth.subtitle": "Chỉ OAuth (token ~/.codex/auth.json) — không fallback CLI.",
        "source.codex.cli.subtitle": "Chỉ `codex app-server` RPC cục bộ — bỏ qua OAuth.",
        "source.claude.auto.subtitle": "Thử OAuth → Web → CLI, lấy cái đầu tiên thành công.",
        "source.claude.oauth.subtitle": "Dùng OAuth token trong Keychain của Claude Code (mặc định).",
        "source.claude.web.subtitle": "Scrape claude.ai qua cookie Safari/Chrome.",
        "source.claude.cli.subtitle": "Chạy `claude` CLI trong PTY (cần CLI cài đặt).",
        "source.claude.api.subtitle": "Anthropic Admin API (cần nhập key bên dưới).",
        "metric.automatic": "Tự động",
        "metric.session": "Phiên (5 giờ)",
        "metric.weekly": "Tuần",
        "region.china": "Trung Quốc (platform.minimaxi.com)",
        "prompt.never": "Không bao giờ",
        "prompt.onlyOnUserAction": "Chỉ khi bấm",
        "prompt.always": "Luôn hỏi",
        "refresh.default": "Mặc định chung",
        "refresh.30s": "30 giây",
        "refresh.1m": "1 phút",
        "refresh.2m": "2 phút",
        "refresh.5m": "5 phút",
        "refresh.10m": "10 phút",
        "refresh.30m": "30 phút",
        "popover.ready": "Sẵn sàng",
        "popover.updating": "Đang cập nhật",
        "popover.refresh": "Refresh",
        "popover.lowestQuota": "Quota thấp nhất",
        "popover.loadingQuota": "Đang tải quota",
        "popover.settings": "Settings…",
        "popover.about": "About BirdNion",
        "popover.quit": "Quit BirdNion",
        "popover.noProviders": "Chưa có nhà cung cấp nào",
        "popover.noProvidersBody": "Mở Settings để chọn nhà cung cấp bạn muốn theo dõi quota AI.",
        "popover.openSettings": "Mở Settings",
        "popover.visibilityOn": "Provider này đang hiển thị trên menu bar. Tắt để ẩn.",
        "popover.visibilityOff": "Provider này đang ẩn khỏi menu bar. Bật để hiển thị.",
        "popover.aboutInfo": "Ứng dụng menu bar macOS để theo dõi quota AI.",
        "button.close": "Đóng",
        "time.justUpdated": "vừa cập nhật",
        "time.secondsAgo": "%d giây trước",
        "time.minutesAgo": "%d phút trước",
        "time.hoursAgo": "%d giờ trước",
        "quota.used": "Đã dùng %d%%",
        "quota.resetSoon": "Reset sắp tới",
        "quota.resetWeekly": "Reset hằng tuần",
        "quota.resetIn5h": "Reset trong 5h",
        "quota.resetInDaysHours": "Reset trong %dd %dh",
        "quota.resetInHoursMinutes": "Reset trong %dh %dm",
        "quota.resetInMinutes": "Reset trong %dm",
        "chart.todayWithDate": "Hôm nay (%@)",
        "chart.today": "Hôm nay",
        "chart.last30Cost": "30d cost",
        "chart.latestTokens": "Latest tokens",
        "chart.topModel": "Top model: %@",
        "chart.estimate": "Estimated from local Claude logs at API rates; token totals are exact, USD are approximate.",
        "chart.estTotal30": "Tổng ước tính (30 ngày)",
        "config.enter": "Nhập",
        "config.save": "Lưu",
        "config.keyTooLong": "API key quá dài (max 256)",
        "config.saved": "Đã lưu. Khởi động lại Claude Code để áp dụng.",
    ]

    private static let en: [String: String] = [
        "language.system": "System",
        "language.english": "English",
        "language.vietnamese": "Vietnamese",
        "settings.tab.general": "General",
        "settings.tab.providers": "Providers",
        "settings.tab.display": "Display",
        "settings.tab.advanced": "Advanced",
        "settings.tab.about": "About",
        "settings.tab.debug": "Debug",
        "settings.section.system": "System",
        "settings.section.usage": "Usage",
        "settings.section.automation": "Automation",
        "settings.section.privacy": "Privacy",
        "settings.section.developer": "Developer",
        "settings.section.files": "Files",
        "settings.section.menuBar": "Menu Bar",
        "settings.section.links": "Links",
        "settings.section.setup": "Setup",
        "settings.section.account": "Accounts",
        "settings.section.quotaWarnings": "Quota Warnings",
        "settings.language.title": "Language",
        "settings.language.subtitle": "Updates the UI immediately and persists for the next launch.",
        "settings.launchAtLogin.title": "Launch at login",
        "settings.launchAtLogin.subtitle": "Open BirdNion automatically when you sign in.",
        "settings.refreshFrequency.title": "Refresh frequency",
        "settings.refreshFrequency.subtitle": "How often BirdNion calls each provider.",
        "settings.statusChecks.title": "Status checks",
        "settings.statusChecks.subtitle": "Poll provider status pages.",
        "settings.sessionNotifications.title": "5-hour session notifications",
        "settings.sessionNotifications.subtitle": "Notify when session quota reaches 0% and recovers.",
        "settings.quotaWarningNotifications.title": "Quota warning notifications",
        "settings.quotaWarningNotifications.subtitle": "Warn when remaining quota falls below your thresholds.",
        "settings.warningThreshold.title": "Warning threshold",
        "settings.warningThreshold.subtitle": "First warning when remaining % reaches this level.",
        "settings.criticalThreshold.title": "Critical threshold",
        "settings.criticalThreshold.subtitle": "Second warning at a lower remaining level.",
        "settings.hidePersonalInfo.title": "Hide personal info",
        "settings.hidePersonalInfo.subtitle": "Mask account email on chips and in the popover.",
        "settings.debugMenu.title": "Show Debug tab",
        "settings.debugMenu.subtitle": "Adds a Debug tab for logs and cache shortcuts.",
        "settings.developer.footer": "Some technical changes may still require reopening the app.",
        "settings.display.footer": "These settings take effect when the renderer supports multiple icons.",
        "settings.mergeIcons.title": "Merge provider icons",
        "settings.mergeIcons.subtitle": "Show one rotating icon for enabled providers.",
        "settings.switcherShowsIcons.title": "Switcher shows icons",
        "settings.switcherShowsIcons.subtitle.on": "Show icons when switching providers from the popover.",
        "settings.switcherShowsIcons.subtitle.off": "Enable “Merge provider icons” first.",
        "settings.debug.footer": "For real probe/fetch-strategy logs, open Console.app and filter by bundle ID.",
        "settings.configFile.title": "Config file",
        "settings.openFinder": "Open Finder",
        "about.openProject": "Open the project page on GitHub",
        "about.tagline": "Track AI quota from your menu bar.",
        "about.version": "version %@ (%@)",
        "provider.search": "Search providers",
        "provider.clearSearch": "Clear",
        "provider.reorderHelp": "Drag to reorder providers",
        "provider.choose": "Choose a provider",
        "provider.enableHelp.on": "Disable polling for this provider",
        "provider.enableHelp.off": "Enable polling for this provider",
        "provider.disabled": "Disabled",
        "provider.notLoaded": "Not loaded",
        "provider.loading": "Loading…",
        "provider.errorPrefix": "Error: %@",
        "provider.remaining": "%d%% left",
        "provider.status": "Status",
        "provider.source": "Source",
        "provider.plan": "Plan",
        "provider.planName": "Plan name",
        "provider.account": "Account",
        "provider.version": "Version",
        "provider.serviceStatus": "Service status",
        "provider.resetCredits": "Resets available",
        "provider.codeReview": "Code review",
        "provider.creditsHistory": "Credits history",
        "provider.buyCredits": "Buy credits",
        "provider.openPage": "Open page",
        "provider.updated": "Updated",
        "provider.reloadHelp": "Reload settings.json and refresh quota",
        "provider.noData.enabled": "No data yet — click refresh.",
        "provider.noData.disabled": "Disabled — no data.",
        "provider.reserve": "%d%% reserve",
        "provider.resetAfter": "Resets in %@",
        "provider.enoughUntilReset": "Enough until reset",
        "provider.mayRunOut": "May run out before reset",
        "provider.credits": "CREDITS",
        "provider.unlimited": "∞ Unlimited",
        "provider.creditsLeft": "%@ left",
        "provider.outOfCredits": "Empty",
        "provider.cost": "COST",
        "provider.usedRemaining": "%d%% used · %@ left",
        "provider.today": "Today",
        "provider.last30": "30 days",
        "provider.email": "EMAIL",
        "provider.organization": "ORG",
        "provider.login": "LOGIN",
        "provider.accountLabel": "Account label",
        "provider.accountLabelPlaceholder": "Optional — leave blank to infer",
        "provider.signIn": "Sign in",
        "provider.codexSignInHint": "Sign in with `codex` in Terminal.",
        "provider.dataSource": "Data source",
        "provider.menuBarMetric": "Menu bar metric",
        "provider.apiRegion": "API region",
        "provider.refreshEvery": "Refresh every",
        "provider.defaultGlobal": "Default = general setting (%@)",
        "provider.cookie": "Cookie",
        "provider.cookiePlaceholder": "Paste Cookie: header from chatgpt.com",
        "provider.cookieClaude": "Claude cookie",
        "provider.manualCookie": "Manual Cookie header",
        "provider.manualCookieHelp": "Open claude.ai in a signed-in browser → DevTools → Network → copy the full `Cookie:` header.",
        "provider.keychainOAuth": "Keychain OAuth",
        "provider.openAIWebExtras": "OpenAI web extras",
        "provider.openAIWebExtrasHelp": "Scan chatgpt.com in a hidden WebView for code-review %, credits, and history. Uses more battery/network — off by default.",
        "provider.claudeConfig": "Claude config…",
        "provider.token": "Token",
        "provider.tokenPlaceholder": "Paste token here",
        "provider.save": "Save",
        "provider.savedSettings": "Saved to ~/.config/birdnion/settings.json.",
        "provider.saveError": "Save failed: %@",
        "provider.quotaWarningsFooter": "Uses global thresholds unless you enable custom thresholds for each window.",
        "provider.sessionWindow": "Session (5 hours)",
        "provider.weekWindow": "Week",
        "provider.customThresholds": "Customize %@ thresholds",
        "provider.inherited": "Inherited: %@",
        "provider.warning": "Warning",
        "provider.critical": "Critical",
        "provider.accountsFooter": "Each account signs in separately. “Add account” opens `codex login` in the browser; the system account (~/.codex) is left untouched.",
        "provider.systemAccount": "System account",
        "provider.accountGeneric": "Account",
        "provider.systemManaged": "System · ~/.codex",
        "provider.appManaged": "Managed by app",
        "provider.reauth": "Sign in again",
        "provider.saveManaged": "Save as managed",
        "provider.addAccount": "Add account",
        "provider.waitingLogin": "Waiting for browser sign-in…",
        "provider.link.codexUsage": "Codex usage page",
        "provider.link.openAIStatus": "OpenAI status",
        "provider.link.changelog": "Changelog",
        "provider.link.minimaxPlan": "Token Plan page",
        "provider.link.openRouterCredits": "OpenRouter credits",
        "provider.link.apiKeys": "API keys",
        "provider.link.deepSeekBalance": "DeepSeek balance",
        "provider.link.codingPlan": "Coding Plan",
        "provider.link.anthropicStatus": "Anthropic status",
        "provider.link.dashboard": "Dashboard",
        "provider.link.status": "Service status",
        "provider.link.usage": "Usage page",
        "provider.link.subscription": "Subscription",
        "provider.link.billing": "Billing",
        "source.auto": "Auto",
        "source.oauth": "OAuth",
        "source.cli": "CLI",
        "source.codex.auto.subtitle": "OAuth, falling back to `codex app-server` CLI on errors (default).",
        "source.codex.oauth.subtitle": "OAuth only (~/.codex/auth.json token) — no CLI fallback.",
        "source.codex.cli.subtitle": "Only local `codex app-server` RPC — skips OAuth.",
        "source.claude.auto.subtitle": "Try OAuth → Web → CLI and use the first successful source.",
        "source.claude.oauth.subtitle": "Use the OAuth token in Claude Code Keychain (default).",
        "source.claude.web.subtitle": "Scrape claude.ai with Safari/Chrome cookies.",
        "source.claude.cli.subtitle": "Run the `claude` CLI in a PTY (requires CLI installed).",
        "source.claude.api.subtitle": "Anthropic Admin API (requires an admin key below).",
        "metric.automatic": "Automatic",
        "metric.session": "Session (5 hours)",
        "metric.weekly": "Week",
        "region.china": "China (platform.minimaxi.com)",
        "prompt.never": "Never",
        "prompt.onlyOnUserAction": "Only on click",
        "prompt.always": "Always ask",
        "refresh.default": "General default",
        "refresh.30s": "30 seconds",
        "refresh.1m": "1 minute",
        "refresh.2m": "2 minutes",
        "refresh.5m": "5 minutes",
        "refresh.10m": "10 minutes",
        "refresh.30m": "30 minutes",
        "popover.ready": "Ready",
        "popover.updating": "Updating",
        "popover.refresh": "Refresh",
        "popover.lowestQuota": "Lowest quota",
        "popover.loadingQuota": "Loading quota",
        "popover.settings": "Settings…",
        "popover.about": "About BirdNion",
        "popover.quit": "Quit BirdNion",
        "popover.noProviders": "No providers enabled",
        "popover.noProvidersBody": "Open Settings to choose which AI quota providers to track.",
        "popover.openSettings": "Open Settings",
        "popover.visibilityOn": "This provider is visible in the menu bar. Turn off to hide it.",
        "popover.visibilityOff": "This provider is hidden from the menu bar. Turn on to show it.",
        "popover.aboutInfo": "macOS menu bar app for tracking AI provider quota.",
        "button.close": "Close",
        "time.justUpdated": "just updated",
        "time.secondsAgo": "%d seconds ago",
        "time.minutesAgo": "%d minutes ago",
        "time.hoursAgo": "%d hours ago",
        "quota.used": "Used %d%%",
        "quota.resetSoon": "Reset soon",
        "quota.resetWeekly": "Resets weekly",
        "quota.resetIn5h": "Resets in 5h",
        "quota.resetInDaysHours": "Resets in %dd %dh",
        "quota.resetInHoursMinutes": "Resets in %dh %dm",
        "quota.resetInMinutes": "Resets in %dm",
        "chart.todayWithDate": "Today (%@)",
        "chart.today": "Today",
        "chart.last30Cost": "30d cost",
        "chart.latestTokens": "Latest tokens",
        "chart.topModel": "Top model: %@",
        "chart.estimate": "Estimated from local Claude logs at API rates; token totals are exact, USD are approximate.",
        "chart.estTotal30": "Est. total (Last 30 days)",
        "config.enter": "Enter",
        "config.save": "Save",
        "config.keyTooLong": "API key is too long (max 256)",
        "config.saved": "Saved. Restart Claude Code to apply.",
    ]
}
